# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f51b6dc510918b565946de09794252b50108e9983380f8332d289a68e18e449870ca4d7ee601bb3177024308e3bad8bab21f588498190fb74d255178a0610610

test:
  secret_key_base: 4d2e51102f91ca9bc4aeee288465f1b1e8266aac9d2db174c6aee11f52939ffab713a5351745c3a8c864dae70698eb83746f0e9f3f0c3ab1202995b44fb1987d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
